# Generated by Django 2.0.3 on 2018-03-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BagItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('size', models.CharField(choices=[('XS', 'extra small'), ('S', 'small'), ('L', 'large'), ('M', 'medium'), ('XL', 'extra large'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('3', '3'), ('4', '4'), ('4', '4'), ('4', '4'), ('4', '4'), ('4', '4'), ('4', '4'), ('4', '4')], max_length=2)),
                ('discount', models.CharField(choices=[('20', 'low'), ('30', 'midrange'), ('50', 'medium'), ('70', 'super')], max_length=2, null=True)),
                ('description', models.CharField(max_length=500)),
                ('image1', models.ImageField(upload_to='image/')),
                ('image2', models.ImageField(upload_to='image/')),
                ('image3', models.ImageField(upload_to='image/')),
                ('brand', models.CharField(max_length=50)),
                ('published_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ship_date', models.DateField(null=True)),
                ('shipping_charge', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoppingBoard.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingBoard.Category')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingBoard.SubCategory'),
        ),
        migrations.AddField(
            model_name='bag',
            name='bag_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagItems', to='shoppingBoard.BagItems'),
        ),
        migrations.AddField(
            model_name='bag',
            name='bag_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagOwner', to=settings.AUTH_USER_MODEL),
        ),
    ]
