# Generated by Django 2.0.3 on 2018-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
