# Generated by Django 2.0.3 on 2018-03-30 05:46

from django.db import migrations, models
import django.db.models.deletion
import shoppingBoard.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingBoard', '0002_inventory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='productSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('XS', 'extra small'), ('S', 'small'), ('L', 'large'), ('M', 'medium'), ('XL', 'extra large'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('3', '3'), ('4', '4'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='size',
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image1',
            field=models.ImageField(upload_to=shoppingBoard.models.image_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image2',
            field=models.ImageField(upload_to=shoppingBoard.models.image_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image3',
            field=models.ImageField(upload_to=shoppingBoard.models.image_path),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.PositiveIntegerField(),
        ),
       
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shoppingBoard.Category'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='shoppingBoard.Inventory'),
        ),
    ]
