# Generated by Django 2.0.4 on 2018-04-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingBoard', '0003_auto_20180330_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='size',
            field=models.CharField(choices=[('BOTTOM CLOTH', (('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'))), ('SHOES', (('3', '3'), ('4', '4'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'))), ('TOP CLOTH', (('XS', 'extra small'), ('S', 'small'), ('L', 'large'), ('M', 'medium'), ('XL', 'extra large')))], max_length=2),
        ),
    ]
