# Generated by Django 2.0.4 on 2018-04-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoppingBoard', '0004_auto_20180418_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.PositiveIntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bag',
            name='bag_items',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='bag_of',
        ),
        migrations.RemoveField(
            model_name='bagitems',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='order_by',
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='BagItems',
        ),
        migrations.AddField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='shoppingBoard.UserData'),
        ),
        migrations.AddField(
            model_name='ordereditems',
            name='order',
            field=models.ForeignKey(default='product', on_delete=django.db.models.deletion.CASCADE, related_name='from_order', to='shoppingBoard.Order'),
        ),
    ]
