# Generated by Django 2.0.4 on 2018-04-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingBoard', '0006_auto_20180421_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ship_date', models.DateField(null=True)),
                ('shipping_charge', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(max_length=2, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_order', to='shoppingBoard.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shoppingBoard.Inventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordereditems',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderedItems',
        ),
    ]
